@baseUrl = http://localhost:8080

##### PessoasController #####
### Criar uma nova pessoa
POST {{baseUrl}}/api/pessoas
Content-Type: application/json

{
    "nome": "João Silva",
    "idade": 25
}

### Atualizar uma pessoa existente
PUT {{baseUrl}}/api/pessoas/019cfdf4-db14-7d0d-95dd-5a98f3872837
Content-Type: application/json

{
    "nome": "João Silva",
    "idade": 29
}

### Excluir uma pessoa
DELETE {{baseUrl}}/api/pessoas/019cfdf4-db14-7d0d-95dd-5a98f3872837
Accept: application/json

### Listar todas as pessoas
GET {{baseUrl}}/api/pessoas
Accept: application/json

### Buscar uma pessoa específica por ID
GET {{baseUrl}}/api/pessoas/019cfdf4-db14-7d0d-95dd-5a98f3872837
Accept: application/json


##### CategoriasController #####

### Criar uma nova categoria
POST {{baseUrl}}/api/categorias
Content-Type: application/json

{
    "nome": "Alimentação",
    "descricao": "Gastos com comida",
    "finalidade": 3
}

### Listar todas as categorias
GET {{baseUrl}}/api/categorias
Accept: application/json

### Buscar uma categoria específica por ID
GET {{baseUrl}}/api/categorias/019cfdf8-d7c1-71bc-a48f-3fbafcdaccd1
Accept: application/json

### Consultar totais por categoria
GET {{baseUrl}}/api/categorias/totais
Accept: application/json

##### TransacoesController #####

### Criar uma nova transação
POST {{baseUrl}}/api/transacoes
Content-Type: application/json

{
    "data": "2026-03-17",
    "valor": 50.00,
    "descricao": "Almoço no restaurante",
    "tipo": 2,
    "pessoaId": "019cfdf4-db14-7d0d-95dd-5a98f3872837",
    "categoriaId": "019cfdf8-d7c1-71bc-a48f-3fbafcdaccd1"
}

### Listar todas as transações
GET {{baseUrl}}/api/transacoes
Accept: application/json

### Buscar uma transação específica por ID
GET {{baseUrl}}/api/transacoes/019cfdfa-4d1a-7793-8fa3-383518f3bf37
Accept: application/json

### Listar todas as transações de uma pessoa específica
GET {{baseUrl}}/api/transacoes/pessoa/019cfdf4-db14-7d0d-95dd-5a98f3872837
Accept: application/json

