@baseUrl = http://localhost:8080

##### PessoasController #####
### Criar uma nova pessoa
POST {{baseUrl}}/api/pessoas
Content-Type: application/json

{
    "nome": "João Silva",
    "idade": 25
}

### Atualizar uma pessoa existente
PUT {{baseUrl}}/api/pessoas/019d008d-6f03-7ac7-b6b9-101d85f668ad
Content-Type: application/json

{
    "nome": "João Silva",
    "idade": 15
}

### Excluir uma pessoa
DELETE {{baseUrl}}/api/pessoas/019d008d-6f03-7ac7-b6b9-101d85f668ad
Accept: application/json

### Listar todas as pessoas
GET {{baseUrl}}/api/pessoas
Accept: application/json

### Buscar uma pessoa específica por ID
GET {{baseUrl}}/api/pessoas/019d008d-6f03-7ac7-b6b9-101d85f668ad
Accept: application/json

### Consultar totais por pessoa
GET {{baseUrl}}/api/pessoas/totais
Accept: application/json


##### CategoriasController #####

### Criar uma nova categoria
POST {{baseUrl}}/api/categorias
Content-Type: application/json

{
    "descricao": "Despesas",
    "finalidade": 1
}

### Listar todas as categorias
GET {{baseUrl}}/api/categorias
Accept: application/json

### Buscar uma categoria específica por ID
GET {{baseUrl}}/api/categorias/019d008e-1a09-785f-8598-afdea770737b
Accept: application/json

### Consultar totais por categoria
GET {{baseUrl}}/api/categorias/totais
Accept: application/json

##### TransacoesController #####

### Criar uma nova transação
POST {{baseUrl}}/api/transacoes
Content-Type: application/json

{
    "data": "2026-03-17",
    "valor": 50.00,
    "descricao": "Receita",
    "tipo": 2,
    "pessoaId": "019d008d-6f03-7ac7-b6b9-101d85f668ad",
    "categoriaId": "019d008f-4247-7d2c-afaa-0b8876d95647"
}

### Listar todas as transações
GET {{baseUrl}}/api/transacoes
Accept: application/json

### Buscar uma transação específica por ID
GET {{baseUrl}}/api/transacoes/019d0092-e571-762a-8877-b9fd810cf474
Accept: application/json

### Listar todas as transações de uma pessoa específica
GET {{baseUrl}}/api/transacoes/pessoa/019d008d-6f03-7ac7-b6b9-101d85f668ad
Accept: application/json

